# -*- coding: utf-8 -*-
"""CardonaBuenaventura_PedroLuis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3LAf7_y_3bdhQhGLwZVj4YIF-kEFXnf
"""

def contieneGC(inString):
  if 'GC' in inString:
    return 'si'
  else:
    return 'no'

print(contieneGC('ATGCATTA'))
print(contieneGC('ATGACATTA'))

def testContieneGC():
  testVals = [('ATGCATTA','si'),
              ('CCCGAGA','no'),
              ('AGAGAGAAGAAGAGAAA','no'),
              ('GAGACCGCC','si'),
              ('CCCCCCCCGAGTTTT','no')
              
            ]
  for (inString, esperado) in testVals:
    respuesta = contieneGC(inString)
    print(inString, ':', respuesta )
    assert respuesta == esperado
  print("!Pruebas superadas ¡")

testContieneGC()